version: '3.8'

services:
  weather-feed:
    build:
      context: ./weather-feed
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=pass1
      - RABBITMQ_QUEUE=queue1

  weather-hub:
    build:
      context: ./weather-hub
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
      clickhouse:
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=pass1
      - RABBITMQ_QUEUE=queue1
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=user1
      - CLICKHOUSE_PASS=pass1
      - CLICKHOUSE_DB=weather_database
      - CLICKHOUSE_TABLE=weather_scores

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user1
      - RABBITMQ_DEFAULT_PASS=pass1
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 5s
      timeout: 5s
      retries: 10

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse
      - ./data.tsv:/docker-entrypoint-initdb.d/data.tsv
      - ./data-loader.sh:/docker-entrypoint-initdb.d/data-loader.sh
    environment:
      - CLICKHOUSE_DB=weather_database
      - CLICKHOUSE_USER=user1
      - CLICKHOUSE_PASSWORD=pass1
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

volumes:
  clickhouse_data:
  clickhouse_logs:
